name: Release

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: 'maven'
    
    - name: Create maven settings.xml
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        servers: |
          [{
            "id": "trombone-mvn-repo",
            "username": "voyanttools",
            "password": "${{secrets.GITHUB_TOKEN}}"
          }]
    
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
      
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.zip
